* Description
# Personal configuration for doom emacs

+ Ready to use with solargraph and rails (with rbenv)
+ Working with JS
+ Some new functions added.
+ Tabnine included

* Prerequisites
 - Git 2.23+
 - Emacs 26.1+ (27 is recommended) with GNUTLS support
 - ripgrep 11.0+
 - GNU find
 - OPTIONAL fd 7.3.0+ (improves file indexing performance for some commands)

* Installation
#+BEGIN_SRC shell
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
git clone https://github.com/otavioschwanck/doom_emacs_dotfiles.git ~/.doom.d
~/.emacs.d/bin/doom install
#+END_SRC

* Performance hacks
  - I've disabled the line numbers to increase the performance and screen space.  If you want to temporary toggle, just press =SPC t l=.  If you want to permanently toggle, just comment the line below:
    #+BEGIN_SRC elisp
                                        ; At ~/.doom.d/editor.el
(setq display-line-numbers-type nil)
    #+END_SRC
  - If tabnine is too slow for your machine, you can disable by commenting this lines:
    #+BEGIN_SRC elisp
;; At ~/.doom.d/editor.el
;; Tabnine for complations
(use-package! company-tabnine)
(defadvice! append-company-tabnine-to-backends-a ()
  :after #'+company-init-backends-h
  (setq-local company-backends (cons 'company-tabnine company-backends)))
(add-hook! 'lsp-completion-mode-hook
  (defun init-company-tabnine-h ()
    (when lsp-completion-mode
      (setq-local company-backends (cons 'company-tabnine company-backends)))))

    #+END_SRC
  - I really recommend you to use gccemacs version, it is very faster, you can install by compiling it: https://www.emacswiki.org/emacs/GccEmacs

* Using Autocomplete
On my doom config, i had done several tweaks to the default autocomplete.

Instead of using enter to select the item in the popup, I use TAB.  The Tab can't go down and up in the autocomplete popup.  Instead of tab, i use =C-j= and =C-k=.

| Key     | Command                                                  |
| Tab     | Select the complation                                    |
| C-j     | Go down on the popup                                     |
| C-k     | Go up on the popup                                       |
| C-i     | See only solargraph complations                          |
| C-p     | Select a similar word instantly                          |
| C-S-p   | See the list of similar words                            |
| C-x C-s | See all the snippets                                     |
| C-enter | Toggle snippet / go foward in snippet                    |
| C-d     | (while snipped is active) Delete the highlighted snippet |

* Solargraph
To configure solargraph for the full potential in your project, follow this steps: https://github.com/otavioschwanck/solargraph-rails

* Getting help
For getting help, access doom official github page: https://github.com/hlissner/doom-emacs
